import "@/styles/globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* <Head>
        <title>{homePageContent.meta.title}</title>
        <meta name="description" content={homePageContent.meta.description} />

        <meta itemProp="name" content={homePageContent.meta.title} />
        <meta
          itemProp="description"
          content={homePageContent.meta.description}
        />
        <meta
          itemProp="image"
          content="https://cash-app-lp.vercel.app/assets/images/cash-app.png"
        />

        <meta property="og:url" content="https://cash-app-lp.vercel.app" />
        <meta property="og:type" content="website" />
        <meta property="og:title" content={homePageContent.meta.title} />
        <meta
          property="og:description"
          content={homePageContent.meta.description}
        />
        <meta
          property="og:image"
          content="https://cash-app-lp.vercel.app/assets/images/cash-app.png"
        />

        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content={homePageContent.meta.title} />
        <meta
          name="twitter:description"
          content={homePageContent.meta.description}
        />
        <meta
          name="twitter:image"
          content="https://cash-app-lp.vercel.app/assets/images/cash-app.png"
        />
      </Head> */}
      <body>{children}</body>
    </html>
  );
}
